name: Manual deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Deploy to dev
        run: echo "Deploying to Dev..."
